# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8842e9ebf84293072e4d49293f19726a6008d9a63723b9e79623ea08ddb008682886b89f0ad9a642f05638fd332ea637438cf547a9637db57ba3f3857a39452e

test:
  secret_key_base: 8b6b879b53f955af0530d37fbd24afbc3221288353969cb5542b175a3b2eff05501aa49b77d1fedcb623a1ecbc77a46875ca94fba9cf6124c0fd73288a4c5fe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
